/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "FuseSDK.h"


#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
// For MIPs (and WP8) platform we do not have asm code for stack switching
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL_LOCK
#endif
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*FuseSDKRegister_t)(FuseSDKCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*FuseSDKUnRegister_t)(FuseSDKCallback cbid, s3eCallback fn);
typedef       void(*FuseSDKStartSession_t)(const char* appID, cfuhash_table_t* options);
typedef       void(*FuseSDKPauseSession_t)();
typedef       void(*FuseSDKResumeSession_t)();
typedef       void(*FuseSDKTerminateSession_t)();
typedef       void(*FuseSDKRegisterForPushNotifications_t)(const char* projectID);
typedef       void(*FuseSDKPreloadAdForZoneID_t)(const char* zoneID);
typedef       bool(*FuseSDKIsAdAvailableForZoneID_t)(const char* zoneID);
typedef       void(*FuseSDKShowAdForZoneID_t)(const char* zoneID, cfuhash_table_t* options);
typedef       void(*FuseSDKRegisterInAppPurchaseAndroid_t)(FusePurchaseStateAndroid purchaseState, const char* purchaseToken, const char* productId, const char* orderId, long purchaseTime, const char* developerPayload, const double* price, const char* currency);
typedef       void(*FuseSDKRegisterInAppPurchaseiOS_t)(FusePurchaseStateiOS purchaseState, const char* receiptData, int recieptDataLength, double* price, const char* currency, const char* productID, const char* transactionID);
typedef       void(*FuseSDKDisplayNotifications_t)();
typedef       void(*FuseSDKDisplayMoreGames_t)();
typedef       void(*FuseSDKRegisterGender_t)(int gender);
typedef       void(*FuseSDKFacebookLogin_t)(const char* facebookId, const char* name, const char* accessToken);
typedef       void(*FuseSDKTwitterLogin_t)(const char* twitterId);
typedef       void(*FuseSDKDeviceLogin_t)(const char* alias);
typedef       void(*FuseSDKFuseLogin_t)(const char* fuseId, const char* alias);
typedef       void(*FuseSDKGameCenterLogin_t)();
typedef       void(*FuseSDKGooglePlayLogin_t)(const char* alias, const char* token);
typedef const char*(*FuseSDKGetOriginalAccountId_t)();
typedef const char*(*FuseSDKGetOriginalAccountAlias_t)();
typedef        int(*FuseSDKGetOriginalAccountType_t)();
typedef const char*(*FuseSDKGetFuseID_t)();
typedef        int(*FuseSDKgamesPlayed_t)();
typedef const char*(*FuseSDKLibraryVersion_t)();
typedef       bool(*FuseSDKConnected_t)();
typedef       void(*FuseSDKTimeFromServer_t)();
typedef       void(*FuseSDKEnableData_t)(bool enable);
typedef const char*(*FuseSDKGetGameConfigurationValue_t)(const char* key);
typedef       void(*FuseSDKRegisterLevel_t)(int level);
typedef       void(*FuseSDKRegisterCurrency_t)(int type, int balance);

/**
 * struct that gets filled in by FuseSDKRegister
 */
typedef struct FuseSDKFuncs
{
    FuseSDKRegister_t m_FuseSDKRegister;
    FuseSDKUnRegister_t m_FuseSDKUnRegister;
    FuseSDKStartSession_t m_FuseSDKStartSession;
    FuseSDKPauseSession_t m_FuseSDKPauseSession;
    FuseSDKResumeSession_t m_FuseSDKResumeSession;
    FuseSDKTerminateSession_t m_FuseSDKTerminateSession;
    FuseSDKRegisterForPushNotifications_t m_FuseSDKRegisterForPushNotifications;
    FuseSDKPreloadAdForZoneID_t m_FuseSDKPreloadAdForZoneID;
    FuseSDKIsAdAvailableForZoneID_t m_FuseSDKIsAdAvailableForZoneID;
    FuseSDKShowAdForZoneID_t m_FuseSDKShowAdForZoneID;
    FuseSDKRegisterInAppPurchaseAndroid_t m_FuseSDKRegisterInAppPurchaseAndroid;
    FuseSDKRegisterInAppPurchaseiOS_t m_FuseSDKRegisterInAppPurchaseiOS;
    FuseSDKDisplayNotifications_t m_FuseSDKDisplayNotifications;
    FuseSDKDisplayMoreGames_t m_FuseSDKDisplayMoreGames;
    FuseSDKRegisterGender_t m_FuseSDKRegisterGender;
    FuseSDKFacebookLogin_t m_FuseSDKFacebookLogin;
    FuseSDKTwitterLogin_t m_FuseSDKTwitterLogin;
    FuseSDKDeviceLogin_t m_FuseSDKDeviceLogin;
    FuseSDKFuseLogin_t m_FuseSDKFuseLogin;
    FuseSDKGameCenterLogin_t m_FuseSDKGameCenterLogin;
    FuseSDKGooglePlayLogin_t m_FuseSDKGooglePlayLogin;
    FuseSDKGetOriginalAccountId_t m_FuseSDKGetOriginalAccountId;
    FuseSDKGetOriginalAccountAlias_t m_FuseSDKGetOriginalAccountAlias;
    FuseSDKGetOriginalAccountType_t m_FuseSDKGetOriginalAccountType;
    FuseSDKGetFuseID_t m_FuseSDKGetFuseID;
    FuseSDKgamesPlayed_t m_FuseSDKgamesPlayed;
    FuseSDKLibraryVersion_t m_FuseSDKLibraryVersion;
    FuseSDKConnected_t m_FuseSDKConnected;
    FuseSDKTimeFromServer_t m_FuseSDKTimeFromServer;
    FuseSDKEnableData_t m_FuseSDKEnableData;
    FuseSDKGetGameConfigurationValue_t m_FuseSDKGetGameConfigurationValue;
    FuseSDKRegisterLevel_t m_FuseSDKRegisterLevel;
    FuseSDKRegisterCurrency_t m_FuseSDKRegisterCurrency;
} FuseSDKFuncs;

static FuseSDKFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xc8b9be9a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: FuseSDK");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xc8b9be9a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool FuseSDKAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult FuseSDKRegister(FuseSDKCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[0] func: FuseSDKRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_FuseSDKRegister(cbid, fn, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult FuseSDKUnRegister(FuseSDKCallback cbid, s3eCallback fn)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[1] func: FuseSDKUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_FuseSDKUnRegister(cbid, fn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void FuseSDKStartSession(const char* appID, cfuhash_table_t* options)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[2] func: FuseSDKStartSession"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKStartSession(appID, options);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKPauseSession()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[3] func: FuseSDKPauseSession"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKPauseSession();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKResumeSession()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[4] func: FuseSDKResumeSession"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKResumeSession();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKTerminateSession()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[5] func: FuseSDKTerminateSession"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKTerminateSession();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKRegisterForPushNotifications(const char* projectID)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[6] func: FuseSDKRegisterForPushNotifications"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKRegisterForPushNotifications(projectID);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKPreloadAdForZoneID(const char* zoneID)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[7] func: FuseSDKPreloadAdForZoneID"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKPreloadAdForZoneID(zoneID);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

bool FuseSDKIsAdAvailableForZoneID(const char* zoneID)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[8] func: FuseSDKIsAdAvailableForZoneID"));

    if (!_extLoad())
		return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_FuseSDKIsAdAvailableForZoneID(zoneID);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void FuseSDKShowAdForZoneID(const char* zoneID, cfuhash_table_t* options)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[9] func: FuseSDKShowAdForZoneID"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKShowAdForZoneID(zoneID, options);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKRegisterInAppPurchaseAndroid(FusePurchaseStateAndroid purchaseState, const char* purchaseToken, const char* productId, const char* orderId, long purchaseTime, const char* developerPayload, const double* price, const char* currency)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[10] func: FuseSDKRegisterInAppPurchaseAndroid"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKRegisterInAppPurchaseAndroid(purchaseState, purchaseToken, productId, orderId, purchaseTime, developerPayload, price, currency);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKRegisterInAppPurchaseiOS(FusePurchaseStateiOS purchaseState, const char* receiptData, int recieptDataLength, double* price, const char* currency, const char* productID, const char* transactionID)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[11] func: FuseSDKRegisterInAppPurchaseiOS"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKRegisterInAppPurchaseiOS(purchaseState, receiptData, recieptDataLength, price, currency, productID, transactionID);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKDisplayNotifications()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[12] func: FuseSDKDisplayNotifications"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKDisplayNotifications();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKDisplayMoreGames()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[13] func: FuseSDKDisplayMoreGames"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKDisplayMoreGames();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKRegisterGender(int gender)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[14] func: FuseSDKRegisterGender"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKRegisterGender(gender);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKFacebookLogin(const char* facebookId, const char* name, const char* accessToken)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[15] func: FuseSDKFacebookLogin"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKFacebookLogin(facebookId, name, accessToken);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKTwitterLogin(const char* twitterId)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[16] func: FuseSDKTwitterLogin"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKTwitterLogin(twitterId);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKDeviceLogin(const char* alias)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[17] func: FuseSDKDeviceLogin"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKDeviceLogin(alias);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKFuseLogin(const char* fuseId, const char* alias)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[18] func: FuseSDKFuseLogin"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKFuseLogin(fuseId, alias);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKGameCenterLogin()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[19] func: FuseSDKGameCenterLogin"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKGameCenterLogin();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKGooglePlayLogin(const char* alias, const char* token)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[20] func: FuseSDKGooglePlayLogin"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKGooglePlayLogin(alias, token);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

const char* FuseSDKGetOriginalAccountId()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[21] func: FuseSDKGetOriginalAccountId"));

    if (!_extLoad())
		return NULL;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_FuseSDKGetOriginalAccountId();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

const char* FuseSDKGetOriginalAccountAlias()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[22] func: FuseSDKGetOriginalAccountAlias"));

    if (!_extLoad())
		return NULL;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_FuseSDKGetOriginalAccountAlias();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

int FuseSDKGetOriginalAccountType()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[23] func: FuseSDKGetOriginalAccountType"));

    if (!_extLoad())
		return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    int ret = g_Ext.m_FuseSDKGetOriginalAccountType();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

const char* FuseSDKGetFuseID()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[24] func: FuseSDKGetFuseID"));

    if (!_extLoad())
		return NULL;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_FuseSDKGetFuseID();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

int FuseSDKgamesPlayed()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[25] func: FuseSDKgamesPlayed"));

    if (!_extLoad())
		return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    int ret = g_Ext.m_FuseSDKgamesPlayed();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

const char* FuseSDKLibraryVersion()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[26] func: FuseSDKLibraryVersion"));

    if (!_extLoad())
		return NULL;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_FuseSDKLibraryVersion();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool FuseSDKConnected()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[27] func: FuseSDKConnected"));

    if (!_extLoad())
		return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_FuseSDKConnected();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void FuseSDKTimeFromServer()
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[28] func: FuseSDKTimeFromServer"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKTimeFromServer();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKEnableData(bool enable)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[29] func: FuseSDKEnableData"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKEnableData(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

const char* FuseSDKGetGameConfigurationValue(const char* key)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[30] func: FuseSDKGetGameConfigurationValue"));

    if (!_extLoad())
		return NULL;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_FuseSDKGetGameConfigurationValue(key);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void FuseSDKRegisterLevel(int level)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[31] func: FuseSDKRegisterLevel"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKRegisterLevel(level);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void FuseSDKRegisterCurrency(int type, int balance)
{
    IwTrace(FUSESDK_VERBOSE, ("calling FuseSDK[32] func: FuseSDKRegisterCurrency"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_FuseSDKRegisterCurrency(type, balance);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}
