/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef FUSEAPI_AUTODEFS_H
#define FUSEAPI_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FUSEAPI_NAME "FuseAPI"
#define S3E_EXT_FUSEAPI_HASH 0xc8b97392

#endif /* !FUSEAPI_AUTODEFS_H */
