/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef FUSESDK_AUTODEFS_H
#define FUSESDK_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FUSESDK_NAME "FuseSDK"
#define S3E_EXT_FUSESDK_HASH 0xc8b9be9a

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("FuseSDK", 38)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !FUSESDK_AUTODEFS_H */
