/*
java implementation of the FuseAPI extension.

Add android-specific functionality here.

These functions are called via JNI from native code.
*/
/*
 * NOTE: This file was originally written by the extension builder, but will not
 * be overwritten (unless --force is specified) and is intended to be modified.
 */
//package com.fuseextension;

import com.ideaworks3d.marmalade.LoaderAPI;
import android.util.Log;
import android.app.Activity;
import android.content.Context;
import com.fusepowered.fuseapi.*;
import com.fusepowered.util.FuseCallback;
import com.fuseextension.*;

class FuseAPI
{
	private final String TAG = "Fuse_Marmalade";
	private static FuseWrapper wrapper = null;
	/*
	private static FuseAPI _this = null;
	private static Activity _activity;
	private static FuseCallback _gameDataCallback = null;
	private static FuseAPIAdCallback _adCallback = null;
	*/
	
	public FuseAPI()
	{
		Log.i(TAG, "FuseAPI initialize ");

		wrapper = new FuseWrapper();

		/*
		_this = this;
		_activity = LoaderAPI.getActivity();
		_gameDataCallback = new FuseAPIGameDataCallback();
		_adCallback = new FuseAPIAdCallback();
		
		com.fusepowered.fuseapi.FuseAPI.initializeFuseAPI(_activity, _activity.getApplicationContext());
		*/
	}

    public void FuseAPIStartSession(String key)
    {
        //Log.i(TAG, "FuseAPIStartSession from autogenerated " + key);
		//wrapper.startSession(key);
    }
    public void FuseAPIShowAd()
    {
        //Log.i(TAG, "FuseAPIShowAd from autogenerated ");
		//wrapper.showAd();
    }
}
